CREATE TABLE teams (
    id BIGSERIAL NOT NULL,
    name VARCHAR(255),
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS players ADD COLUMN team_id BIGINT;

ALTER TABLE IF EXISTS players
ADD CONSTRAINT FK_PLAYERS_TEAM_ID_TEAMS_ID
FOREIGN KEY (team_id) REFERENCES teams (id);